// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Group.proto

package com.ljh.gamedemo.proto.protoc;

public final class GroupProto {
  private GroupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Group)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 groupId = 1;</code>
     */
    long getGroupId();

    /**
     * <code>.Role leader = 2;</code>
     */
    boolean hasLeader();
    /**
     * <code>.Role leader = 2;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.Role getLeader();
    /**
     * <code>.Role leader = 2;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getLeaderOrBuilder();

    /**
     * <code>repeated .Role members = 3;</code>
     */
    java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role> 
        getMembersList();
    /**
     * <code>repeated .Role members = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.Role getMembers(int index);
    /**
     * <code>repeated .Role members = 3;</code>
     */
    int getMembersCount();
    /**
     * <code>repeated .Role members = 3;</code>
     */
    java.util.List<? extends com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
        getMembersOrBuilderList();
    /**
     * <code>repeated .Role members = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getMembersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Group}
   */
  public  static final class Group extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Group)
      GroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Group.newBuilder() to construct.
    private Group(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Group() {
      members_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Group();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Group(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              groupId_ = input.readInt64();
              break;
            }
            case 18: {
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder subBuilder = null;
              if (leader_ != null) {
                subBuilder = leader_.toBuilder();
              }
              leader_ = input.readMessage(com.ljh.gamedemo.proto.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(leader_);
                leader_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                members_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.RoleProto.Role>();
                mutable_bitField0_ |= 0x00000001;
              }
              members_.add(
                  input.readMessage(com.ljh.gamedemo.proto.protoc.RoleProto.Role.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          members_ = java.util.Collections.unmodifiableList(members_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.GroupProto.internal_static_Group_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.GroupProto.internal_static_Group_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.GroupProto.Group.class, com.ljh.gamedemo.proto.protoc.GroupProto.Group.Builder.class);
    }

    public static final int GROUPID_FIELD_NUMBER = 1;
    private long groupId_;
    /**
     * <code>int64 groupId = 1;</code>
     */
    public long getGroupId() {
      return groupId_;
    }

    public static final int LEADER_FIELD_NUMBER = 2;
    private com.ljh.gamedemo.proto.protoc.RoleProto.Role leader_;
    /**
     * <code>.Role leader = 2;</code>
     */
    public boolean hasLeader() {
      return leader_ != null;
    }
    /**
     * <code>.Role leader = 2;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.Role getLeader() {
      return leader_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : leader_;
    }
    /**
     * <code>.Role leader = 2;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getLeaderOrBuilder() {
      return getLeader();
    }

    public static final int MEMBERS_FIELD_NUMBER = 3;
    private java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role> members_;
    /**
     * <code>repeated .Role members = 3;</code>
     */
    public java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role> getMembersList() {
      return members_;
    }
    /**
     * <code>repeated .Role members = 3;</code>
     */
    public java.util.List<? extends com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
        getMembersOrBuilderList() {
      return members_;
    }
    /**
     * <code>repeated .Role members = 3;</code>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated .Role members = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.Role getMembers(int index) {
      return members_.get(index);
    }
    /**
     * <code>repeated .Role members = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getMembersOrBuilder(
        int index) {
      return members_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (groupId_ != 0L) {
        output.writeInt64(1, groupId_);
      }
      if (leader_ != null) {
        output.writeMessage(2, getLeader());
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeMessage(3, members_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (groupId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, groupId_);
      }
      if (leader_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLeader());
      }
      for (int i = 0; i < members_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, members_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.GroupProto.Group)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.GroupProto.Group other = (com.ljh.gamedemo.proto.protoc.GroupProto.Group) obj;

      if (getGroupId()
          != other.getGroupId()) return false;
      if (hasLeader() != other.hasLeader()) return false;
      if (hasLeader()) {
        if (!getLeader()
            .equals(other.getLeader())) return false;
      }
      if (!getMembersList()
          .equals(other.getMembersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroupId());
      if (hasLeader()) {
        hash = (37 * hash) + LEADER_FIELD_NUMBER;
        hash = (53 * hash) + getLeader().hashCode();
      }
      if (getMembersCount() > 0) {
        hash = (37 * hash) + MEMBERS_FIELD_NUMBER;
        hash = (53 * hash) + getMembersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.GroupProto.Group prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Group}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Group)
        com.ljh.gamedemo.proto.protoc.GroupProto.GroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.GroupProto.internal_static_Group_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.GroupProto.internal_static_Group_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.GroupProto.Group.class, com.ljh.gamedemo.proto.protoc.GroupProto.Group.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.GroupProto.Group.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMembersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        groupId_ = 0L;

        if (leaderBuilder_ == null) {
          leader_ = null;
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          membersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.GroupProto.internal_static_Group_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.GroupProto.Group getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.GroupProto.Group.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.GroupProto.Group build() {
        com.ljh.gamedemo.proto.protoc.GroupProto.Group result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.GroupProto.Group buildPartial() {
        com.ljh.gamedemo.proto.protoc.GroupProto.Group result = new com.ljh.gamedemo.proto.protoc.GroupProto.Group(this);
        int from_bitField0_ = bitField0_;
        result.groupId_ = groupId_;
        if (leaderBuilder_ == null) {
          result.leader_ = leader_;
        } else {
          result.leader_ = leaderBuilder_.build();
        }
        if (membersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            members_ = java.util.Collections.unmodifiableList(members_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.members_ = members_;
        } else {
          result.members_ = membersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.GroupProto.Group) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.GroupProto.Group)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.GroupProto.Group other) {
        if (other == com.ljh.gamedemo.proto.protoc.GroupProto.Group.getDefaultInstance()) return this;
        if (other.getGroupId() != 0L) {
          setGroupId(other.getGroupId());
        }
        if (other.hasLeader()) {
          mergeLeader(other.getLeader());
        }
        if (membersBuilder_ == null) {
          if (!other.members_.isEmpty()) {
            if (members_.isEmpty()) {
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMembersIsMutable();
              members_.addAll(other.members_);
            }
            onChanged();
          }
        } else {
          if (!other.members_.isEmpty()) {
            if (membersBuilder_.isEmpty()) {
              membersBuilder_.dispose();
              membersBuilder_ = null;
              members_ = other.members_;
              bitField0_ = (bitField0_ & ~0x00000001);
              membersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMembersFieldBuilder() : null;
            } else {
              membersBuilder_.addAllMessages(other.members_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.GroupProto.Group parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.GroupProto.Group) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long groupId_ ;
      /**
       * <code>int64 groupId = 1;</code>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>int64 groupId = 1;</code>
       */
      public Builder setGroupId(long value) {
        
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 groupId = 1;</code>
       */
      public Builder clearGroupId() {
        
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private com.ljh.gamedemo.proto.protoc.RoleProto.Role leader_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> leaderBuilder_;
      /**
       * <code>.Role leader = 2;</code>
       */
      public boolean hasLeader() {
        return leaderBuilder_ != null || leader_ != null;
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role getLeader() {
        if (leaderBuilder_ == null) {
          return leader_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : leader_;
        } else {
          return leaderBuilder_.getMessage();
        }
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public Builder setLeader(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (leaderBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          leader_ = value;
          onChanged();
        } else {
          leaderBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public Builder setLeader(
          com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (leaderBuilder_ == null) {
          leader_ = builderForValue.build();
          onChanged();
        } else {
          leaderBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public Builder mergeLeader(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (leaderBuilder_ == null) {
          if (leader_ != null) {
            leader_ =
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.newBuilder(leader_).mergeFrom(value).buildPartial();
          } else {
            leader_ = value;
          }
          onChanged();
        } else {
          leaderBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public Builder clearLeader() {
        if (leaderBuilder_ == null) {
          leader_ = null;
          onChanged();
        } else {
          leader_ = null;
          leaderBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder getLeaderBuilder() {
        
        onChanged();
        return getLeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getLeaderOrBuilder() {
        if (leaderBuilder_ != null) {
          return leaderBuilder_.getMessageOrBuilder();
        } else {
          return leader_ == null ?
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : leader_;
        }
      }
      /**
       * <code>.Role leader = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
          getLeaderFieldBuilder() {
        if (leaderBuilder_ == null) {
          leaderBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder>(
                  getLeader(),
                  getParentForChildren(),
                  isClean());
          leader_ = null;
        }
        return leaderBuilder_;
      }

      private java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role> members_ =
        java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          members_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.RoleProto.Role>(members_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> membersBuilder_;

      /**
       * <code>repeated .Role members = 3;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role> getMembersList() {
        if (membersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(members_);
        } else {
          return membersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public int getMembersCount() {
        if (membersBuilder_ == null) {
          return members_.size();
        } else {
          return membersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role getMembers(int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);
        } else {
          return membersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder setMembers(
          int index, com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.set(index, value);
          onChanged();
        } else {
          membersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder setMembers(
          int index, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.set(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder addMembers(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(value);
          onChanged();
        } else {
          membersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder addMembers(
          int index, com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (membersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMembersIsMutable();
          members_.add(index, value);
          onChanged();
        } else {
          membersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder addMembers(
          com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder addMembers(
          int index, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.add(index, builderForValue.build());
          onChanged();
        } else {
          membersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder addAllMembers(
          java.lang.Iterable<? extends com.ljh.gamedemo.proto.protoc.RoleProto.Role> values) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, members_);
          onChanged();
        } else {
          membersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder clearMembers() {
        if (membersBuilder_ == null) {
          members_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          membersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public Builder removeMembers(int index) {
        if (membersBuilder_ == null) {
          ensureMembersIsMutable();
          members_.remove(index);
          onChanged();
        } else {
          membersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder getMembersBuilder(
          int index) {
        return getMembersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getMembersOrBuilder(
          int index) {
        if (membersBuilder_ == null) {
          return members_.get(index);  } else {
          return membersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public java.util.List<? extends com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
           getMembersOrBuilderList() {
        if (membersBuilder_ != null) {
          return membersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(members_);
        }
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder addMembersBuilder() {
        return getMembersFieldBuilder().addBuilder(
            com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance());
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder addMembersBuilder(
          int index) {
        return getMembersFieldBuilder().addBuilder(
            index, com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance());
      }
      /**
       * <code>repeated .Role members = 3;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder> 
           getMembersBuilderList() {
        return getMembersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
          getMembersFieldBuilder() {
        if (membersBuilder_ == null) {
          membersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder>(
                  members_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          members_ = null;
        }
        return membersBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Group)
    }

    // @@protoc_insertion_point(class_scope:Group)
    private static final com.ljh.gamedemo.proto.protoc.GroupProto.Group DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.GroupProto.Group();
    }

    public static com.ljh.gamedemo.proto.protoc.GroupProto.Group getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Group>
        PARSER = new com.google.protobuf.AbstractParser<Group>() {
      @java.lang.Override
      public Group parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Group(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Group> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Group> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.GroupProto.Group getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Group_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Group_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Group.proto\032\nRole.proto\"G\n\005Group\022\017\n\007gr" +
      "oupId\030\001 \001(\003\022\025\n\006leader\030\002 \001(\0132\005.Role\022\026\n\007me" +
      "mbers\030\003 \003(\0132\005.RoleB+\n\035com.ljh.gamedemo.p" +
      "roto.protocB\nGroupProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljh.gamedemo.proto.protoc.RoleProto.getDescriptor(),
        });
    internal_static_Group_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Group_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Group_descriptor,
        new java.lang.String[] { "GroupId", "Leader", "Members", });
    com.ljh.gamedemo.proto.protoc.RoleProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
