// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgEmail.proto

package com.ljh.gamedemo.proto.protoc;

public final class MsgEmailProto {
  private MsgEmailProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 取得邮件信息
     * </pre>
     *
     * <code>READ = 0;</code>
     */
    READ(0),
    /**
     * <pre>
     * 接收邮件物品
     * </pre>
     *
     * <code>RECEIVE = 1;</code>
     */
    RECEIVE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 取得邮件信息
     * </pre>
     *
     * <code>READ = 0;</code>
     */
    public static final int READ_VALUE = 0;
    /**
     * <pre>
     * 接收邮件物品
     * </pre>
     *
     * <code>RECEIVE = 1;</code>
     */
    public static final int RECEIVE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return READ;
        case 1: return RECEIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgEmailProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestEmailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestEmail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <pre>
     * email Id
     * </pre>
     *
     * <code>int64 eid = 2;</code>
     */
    long getEid();

    /**
     * <code>.RequestType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>.RequestType type = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType();
  }
  /**
   * Protobuf type {@code RequestEmail}
   */
  public  static final class RequestEmail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestEmail)
      RequestEmailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestEmail.newBuilder() to construct.
    private RequestEmail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestEmail() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestEmail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestEmail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 16: {

              eid_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_RequestEmail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_RequestEmail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.class, com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int EID_FIELD_NUMBER = 2;
    private long eid_;
    /**
     * <pre>
     * email Id
     * </pre>
     *
     * <code>int64 eid = 2;</code>
     */
    public long getEid() {
      return eid_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.RequestType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RequestType type = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.valueOf(type_);
      return result == null ? com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (eid_ != 0L) {
        output.writeInt64(2, eid_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.READ.getNumber()) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (eid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, eid_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.READ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail other = (com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getEid()
          != other.getEid()) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + EID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEid());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestEmail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestEmail)
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_RequestEmail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_RequestEmail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.class, com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        eid_ = 0L;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_RequestEmail_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail build() {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail buildPartial() {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail result = new com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail(this);
        result.userId_ = userId_;
        result.eid_ = eid_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail other) {
        if (other == com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getEid() != 0L) {
          setEid(other.getEid());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long eid_ ;
      /**
       * <pre>
       * email Id
       * </pre>
       *
       * <code>int64 eid = 2;</code>
       */
      public long getEid() {
        return eid_;
      }
      /**
       * <pre>
       * email Id
       * </pre>
       *
       * <code>int64 eid = 2;</code>
       */
      public Builder setEid(long value) {
        
        eid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * email Id
       * </pre>
       *
       * <code>int64 eid = 2;</code>
       */
      public Builder clearEid() {
        
        eid_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RequestType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.valueOf(type_);
        return result == null ? com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setType(com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestEmail)
    }

    // @@protoc_insertion_point(class_scope:RequestEmail)
    private static final com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail();
    }

    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestEmail>
        PARSER = new com.google.protobuf.AbstractParser<RequestEmail>() {
      @java.lang.Override
      public RequestEmail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestEmail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestEmail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestEmail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestEmail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseEmailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseEmail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.RequestType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>.RequestType type = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType();

    /**
     * <code>.Email email = 4;</code>
     */
    boolean hasEmail();
    /**
     * <code>.Email email = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.EmailProto.Email getEmail();
    /**
     * <code>.Email email = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder getEmailOrBuilder();
  }
  /**
   * Protobuf type {@code ResponseEmail}
   */
  public  static final class ResponseEmail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseEmail)
      ResponseEmailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseEmail.newBuilder() to construct.
    private ResponseEmail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseEmail() {
      content_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseEmail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseEmail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {
              com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder subBuilder = null;
              if (email_ != null) {
                subBuilder = email_.toBuilder();
              }
              email_ = input.readMessage(com.ljh.gamedemo.proto.protoc.EmailProto.Email.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(email_);
                email_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_ResponseEmail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_ResponseEmail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.class, com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.RequestType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RequestType type = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.valueOf(type_);
      return result == null ? com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int EMAIL_FIELD_NUMBER = 4;
    private com.ljh.gamedemo.proto.protoc.EmailProto.Email email_;
    /**
     * <code>.Email email = 4;</code>
     */
    public boolean hasEmail() {
      return email_ != null;
    }
    /**
     * <code>.Email email = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.EmailProto.Email getEmail() {
      return email_ == null ? com.ljh.gamedemo.proto.protoc.EmailProto.Email.getDefaultInstance() : email_;
    }
    /**
     * <code>.Email email = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder getEmailOrBuilder() {
      return getEmail();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.READ.getNumber()) {
        output.writeEnum(3, type_);
      }
      if (email_ != null) {
        output.writeMessage(4, getEmail());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.READ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      if (email_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getEmail());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail other = (com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail) obj;

      if (getResult()
          != other.getResult()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (hasEmail() != other.hasEmail()) return false;
      if (hasEmail()) {
        if (!getEmail()
            .equals(other.getEmail())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasEmail()) {
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseEmail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseEmail)
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_ResponseEmail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_ResponseEmail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.class, com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        content_ = "";

        type_ = 0;

        if (emailBuilder_ == null) {
          email_ = null;
        } else {
          email_ = null;
          emailBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.internal_static_ResponseEmail_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail build() {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail buildPartial() {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail result = new com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail(this);
        result.result_ = result_;
        result.content_ = content_;
        result.type_ = type_;
        if (emailBuilder_ == null) {
          result.email_ = email_;
        } else {
          result.email_ = emailBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail other) {
        if (other == com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasEmail()) {
          mergeEmail(other.getEmail());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RequestType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.valueOf(type_);
        return result == null ? com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setType(com.ljh.gamedemo.proto.protoc.MsgEmailProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.ljh.gamedemo.proto.protoc.EmailProto.Email email_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.EmailProto.Email, com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder, com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder> emailBuilder_;
      /**
       * <code>.Email email = 4;</code>
       */
      public boolean hasEmail() {
        return emailBuilder_ != null || email_ != null;
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EmailProto.Email getEmail() {
        if (emailBuilder_ == null) {
          return email_ == null ? com.ljh.gamedemo.proto.protoc.EmailProto.Email.getDefaultInstance() : email_;
        } else {
          return emailBuilder_.getMessage();
        }
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public Builder setEmail(com.ljh.gamedemo.proto.protoc.EmailProto.Email value) {
        if (emailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          email_ = value;
          onChanged();
        } else {
          emailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public Builder setEmail(
          com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder builderForValue) {
        if (emailBuilder_ == null) {
          email_ = builderForValue.build();
          onChanged();
        } else {
          emailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public Builder mergeEmail(com.ljh.gamedemo.proto.protoc.EmailProto.Email value) {
        if (emailBuilder_ == null) {
          if (email_ != null) {
            email_ =
              com.ljh.gamedemo.proto.protoc.EmailProto.Email.newBuilder(email_).mergeFrom(value).buildPartial();
          } else {
            email_ = value;
          }
          onChanged();
        } else {
          emailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public Builder clearEmail() {
        if (emailBuilder_ == null) {
          email_ = null;
          onChanged();
        } else {
          email_ = null;
          emailBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder getEmailBuilder() {
        
        onChanged();
        return getEmailFieldBuilder().getBuilder();
      }
      /**
       * <code>.Email email = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder getEmailOrBuilder() {
        if (emailBuilder_ != null) {
          return emailBuilder_.getMessageOrBuilder();
        } else {
          return email_ == null ?
              com.ljh.gamedemo.proto.protoc.EmailProto.Email.getDefaultInstance() : email_;
        }
      }
      /**
       * <code>.Email email = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.EmailProto.Email, com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder, com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder> 
          getEmailFieldBuilder() {
        if (emailBuilder_ == null) {
          emailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.EmailProto.Email, com.ljh.gamedemo.proto.protoc.EmailProto.Email.Builder, com.ljh.gamedemo.proto.protoc.EmailProto.EmailOrBuilder>(
                  getEmail(),
                  getParentForChildren(),
                  isClean());
          email_ = null;
        }
        return emailBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseEmail)
    }

    // @@protoc_insertion_point(class_scope:ResponseEmail)
    private static final com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail();
    }

    public static com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseEmail>
        PARSER = new com.google.protobuf.AbstractParser<ResponseEmail>() {
      @java.lang.Override
      public ResponseEmail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseEmail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseEmail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseEmail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.MsgEmailProto.ResponseEmail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestEmail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestEmail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseEmail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseEmail_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MsgEmail.proto\032\013Email.proto\"G\n\014Request" +
      "Email\022\016\n\006userId\030\001 \001(\003\022\013\n\003eid\030\002 \001(\003\022\032\n\004ty" +
      "pe\030\003 \001(\0162\014.RequestType\"c\n\rResponseEmail\022" +
      "\016\n\006result\030\001 \001(\005\022\017\n\007content\030\002 \001(\t\022\032\n\004type" +
      "\030\003 \001(\0162\014.RequestType\022\025\n\005email\030\004 \001(\0132\006.Em" +
      "ail*$\n\013RequestType\022\010\n\004READ\020\000\022\013\n\007RECEIVE\020" +
      "\001B.\n\035com.ljh.gamedemo.proto.protocB\rMsgE" +
      "mailProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljh.gamedemo.proto.protoc.EmailProto.getDescriptor(),
        });
    internal_static_RequestEmail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestEmail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestEmail_descriptor,
        new java.lang.String[] { "UserId", "Eid", "Type", });
    internal_static_ResponseEmail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseEmail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseEmail_descriptor,
        new java.lang.String[] { "Result", "Content", "Type", "Email", });
    com.ljh.gamedemo.proto.protoc.EmailProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
