// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgMall.proto

package com.ljh.gamedemo.proto.protoc;

public final class MsgMallProto {
  private MsgMallProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code RequestType}
   */
  public enum RequestType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MALL = 0;</code>
     */
    MALL(0),
    /**
     * <code>BUY = 1;</code>
     */
    BUY(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MALL = 0;</code>
     */
    public static final int MALL_VALUE = 0;
    /**
     * <code>BUY = 1;</code>
     */
    public static final int BUY_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RequestType valueOf(int value) {
      return forNumber(value);
    }

    public static RequestType forNumber(int value) {
      switch (value) {
        case 0: return MALL;
        case 1: return BUY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RequestType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
            public RequestType findValueByNumber(int number) {
              return RequestType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgMallProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final RequestType[] VALUES = values();

    public static RequestType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RequestType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RequestType)
  }

  public interface RequestMallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMall)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 userId = 1;</code>
     */
    long getUserId();

    /**
     * <code>int64 cId = 2;</code>
     */
    long getCId();

    /**
     * <code>.RequestType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>.RequestType type = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType();
  }
  /**
   * Protobuf type {@code RequestMall}
   */
  public  static final class RequestMall extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMall)
      RequestMallOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMall.newBuilder() to construct.
    private RequestMall(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMall() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestMall();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              userId_ = input.readInt64();
              break;
            }
            case 16: {

              cId_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_RequestMall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_RequestMall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.class, com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private long userId_;
    /**
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }

    public static final int CID_FIELD_NUMBER = 2;
    private long cId_;
    /**
     * <code>int64 cId = 2;</code>
     */
    public long getCId() {
      return cId_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.RequestType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RequestType type = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.valueOf(type_);
      return result == null ? com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (userId_ != 0L) {
        output.writeInt64(1, userId_);
      }
      if (cId_ != 0L) {
        output.writeInt64(2, cId_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.MALL.getNumber()) {
        output.writeEnum(3, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, userId_);
      }
      if (cId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, cId_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.MALL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall other = (com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall) obj;

      if (getUserId()
          != other.getUserId()) return false;
      if (getCId()
          != other.getCId()) return false;
      if (type_ != other.type_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + CID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RequestMall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMall)
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_RequestMall_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_RequestMall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.class, com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        userId_ = 0L;

        cId_ = 0L;

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_RequestMall_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall build() {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall buildPartial() {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall result = new com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall(this);
        result.userId_ = userId_;
        result.cId_ = cId_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall other) {
        if (other == com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall.getDefaultInstance()) return this;
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (other.getCId() != 0L) {
          setCId(other.getCId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 userId = 1;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private long cId_ ;
      /**
       * <code>int64 cId = 2;</code>
       */
      public long getCId() {
        return cId_;
      }
      /**
       * <code>int64 cId = 2;</code>
       */
      public Builder setCId(long value) {
        
        cId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cId = 2;</code>
       */
      public Builder clearCId() {
        
        cId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RequestType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.valueOf(type_);
        return result == null ? com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setType(com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMall)
    }

    // @@protoc_insertion_point(class_scope:RequestMall)
    private static final com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall();
    }

    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMall>
        PARSER = new com.google.protobuf.AbstractParser<RequestMall>() {
      @java.lang.Override
      public RequestMall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMall(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMall> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMall> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestMall getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMallOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ResponseMall)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <code>string content = 2;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 2;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>.RequestType type = 3;</code>
     */
    int getTypeValue();
    /**
     * <code>.RequestType type = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType();

    /**
     * <code>repeated .Items items = 4;</code>
     */
    java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items> 
        getItemsList();
    /**
     * <code>repeated .Items items = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.ItemsProto.Items getItems(int index);
    /**
     * <code>repeated .Items items = 4;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .Items items = 4;</code>
     */
    java.util.List<? extends com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .Items items = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder getItemsOrBuilder(
        int index);

    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip> 
        getEquipList();
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    com.ljh.gamedemo.proto.protoc.EquipProto.Equip getEquip(int index);
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    int getEquipCount();
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    java.util.List<? extends com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder> 
        getEquipOrBuilderList();
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder getEquipOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ResponseMall}
   */
  public  static final class ResponseMall extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ResponseMall)
      ResponseMallOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMall.newBuilder() to construct.
    private ResponseMall(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMall() {
      content_ = "";
      type_ = 0;
      items_ = java.util.Collections.emptyList();
      equip_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseMall();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMall(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.ItemsProto.Items>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(com.ljh.gamedemo.proto.protoc.ItemsProto.Items.parser(), extensionRegistry));
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                equip_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.EquipProto.Equip>();
                mutable_bitField0_ |= 0x00000002;
              }
              equip_.add(
                  input.readMessage(com.ljh.gamedemo.proto.protoc.EquipProto.Equip.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          equip_ = java.util.Collections.unmodifiableList(equip_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_ResponseMall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_ResponseMall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.class, com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 2;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 2;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>.RequestType type = 3;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.RequestType type = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType() {
      @SuppressWarnings("deprecation")
      com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.valueOf(type_);
      return result == null ? com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.UNRECOGNIZED : result;
    }

    public static final int ITEMS_FIELD_NUMBER = 4;
    private java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items> items_;
    /**
     * <code>repeated .Items items = 4;</code>
     */
    public java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .Items items = 4;</code>
     */
    public java.util.List<? extends com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .Items items = 4;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .Items items = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.ItemsProto.Items getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .Items items = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    public static final int EQUIP_FIELD_NUMBER = 5;
    private java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip> equip_;
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    public java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip> getEquipList() {
      return equip_;
    }
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    public java.util.List<? extends com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder> 
        getEquipOrBuilderList() {
      return equip_;
    }
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    public int getEquipCount() {
      return equip_.size();
    }
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    public com.ljh.gamedemo.proto.protoc.EquipProto.Equip getEquip(int index) {
      return equip_.get(index);
    }
    /**
     * <code>repeated .Equip equip = 5;</code>
     */
    public com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder getEquipOrBuilder(
        int index) {
      return equip_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, content_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.MALL.getNumber()) {
        output.writeEnum(3, type_);
      }
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(4, items_.get(i));
      }
      for (int i = 0; i < equip_.size(); i++) {
        output.writeMessage(5, equip_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, content_);
      }
      if (type_ != com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.MALL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_);
      }
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, items_.get(i));
      }
      for (int i = 0; i < equip_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, equip_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall other = (com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall) obj;

      if (getResult()
          != other.getResult()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (type_ != other.type_) return false;
      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!getEquipList()
          .equals(other.getEquipList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      if (getEquipCount() > 0) {
        hash = (37 * hash) + EQUIP_FIELD_NUMBER;
        hash = (53 * hash) + getEquipList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ResponseMall}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ResponseMall)
        com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMallOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_ResponseMall_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_ResponseMall_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.class, com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
          getEquipFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = 0;

        content_ = "";

        type_ = 0;

        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        if (equipBuilder_ == null) {
          equip_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          equipBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.internal_static_ResponseMall_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall build() {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall buildPartial() {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall result = new com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall(this);
        int from_bitField0_ = bitField0_;
        result.result_ = result_;
        result.content_ = content_;
        result.type_ = type_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (equipBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            equip_ = java.util.Collections.unmodifiableList(equip_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.equip_ = equip_;
        } else {
          result.equip_ = equipBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall other) {
        if (other == com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (equipBuilder_ == null) {
          if (!other.equip_.isEmpty()) {
            if (equip_.isEmpty()) {
              equip_ = other.equip_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEquipIsMutable();
              equip_.addAll(other.equip_);
            }
            onChanged();
          }
        } else {
          if (!other.equip_.isEmpty()) {
            if (equipBuilder_.isEmpty()) {
              equipBuilder_.dispose();
              equipBuilder_ = null;
              equip_ = other.equip_;
              bitField0_ = (bitField0_ & ~0x00000002);
              equipBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEquipFieldBuilder() : null;
            } else {
              equipBuilder_.addAllMessages(other.equip_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int result_ ;
      /**
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 2;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 2;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.RequestType type = 3;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType getType() {
        @SuppressWarnings("deprecation")
        com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType result = com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.valueOf(type_);
        return result == null ? com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder setType(com.ljh.gamedemo.proto.protoc.MsgMallProto.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestType type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.ItemsProto.Items>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.ItemsProto.Items, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder, com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .Items items = 4;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.ItemsProto.Items getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder setItems(
          int index, com.ljh.gamedemo.proto.protoc.ItemsProto.Items value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder setItems(
          int index, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder addItems(com.ljh.gamedemo.proto.protoc.ItemsProto.Items value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder addItems(
          int index, com.ljh.gamedemo.proto.protoc.ItemsProto.Items value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder addItems(
          com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder addItems(
          int index, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends com.ljh.gamedemo.proto.protoc.ItemsProto.Items> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public java.util.List<? extends com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            com.ljh.gamedemo.proto.protoc.ItemsProto.Items.getDefaultInstance());
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.getDefaultInstance());
      }
      /**
       * <code>repeated .Items items = 4;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.ItemsProto.Items, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder, com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.ItemsProto.Items, com.ljh.gamedemo.proto.protoc.ItemsProto.Items.Builder, com.ljh.gamedemo.proto.protoc.ItemsProto.ItemsOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      private java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip> equip_ =
        java.util.Collections.emptyList();
      private void ensureEquipIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          equip_ = new java.util.ArrayList<com.ljh.gamedemo.proto.protoc.EquipProto.Equip>(equip_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.EquipProto.Equip, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder, com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder> equipBuilder_;

      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip> getEquipList() {
        if (equipBuilder_ == null) {
          return java.util.Collections.unmodifiableList(equip_);
        } else {
          return equipBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public int getEquipCount() {
        if (equipBuilder_ == null) {
          return equip_.size();
        } else {
          return equipBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EquipProto.Equip getEquip(int index) {
        if (equipBuilder_ == null) {
          return equip_.get(index);
        } else {
          return equipBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder setEquip(
          int index, com.ljh.gamedemo.proto.protoc.EquipProto.Equip value) {
        if (equipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipIsMutable();
          equip_.set(index, value);
          onChanged();
        } else {
          equipBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder setEquip(
          int index, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder builderForValue) {
        if (equipBuilder_ == null) {
          ensureEquipIsMutable();
          equip_.set(index, builderForValue.build());
          onChanged();
        } else {
          equipBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder addEquip(com.ljh.gamedemo.proto.protoc.EquipProto.Equip value) {
        if (equipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipIsMutable();
          equip_.add(value);
          onChanged();
        } else {
          equipBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder addEquip(
          int index, com.ljh.gamedemo.proto.protoc.EquipProto.Equip value) {
        if (equipBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEquipIsMutable();
          equip_.add(index, value);
          onChanged();
        } else {
          equipBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder addEquip(
          com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder builderForValue) {
        if (equipBuilder_ == null) {
          ensureEquipIsMutable();
          equip_.add(builderForValue.build());
          onChanged();
        } else {
          equipBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder addEquip(
          int index, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder builderForValue) {
        if (equipBuilder_ == null) {
          ensureEquipIsMutable();
          equip_.add(index, builderForValue.build());
          onChanged();
        } else {
          equipBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder addAllEquip(
          java.lang.Iterable<? extends com.ljh.gamedemo.proto.protoc.EquipProto.Equip> values) {
        if (equipBuilder_ == null) {
          ensureEquipIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, equip_);
          onChanged();
        } else {
          equipBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder clearEquip() {
        if (equipBuilder_ == null) {
          equip_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          equipBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public Builder removeEquip(int index) {
        if (equipBuilder_ == null) {
          ensureEquipIsMutable();
          equip_.remove(index);
          onChanged();
        } else {
          equipBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder getEquipBuilder(
          int index) {
        return getEquipFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder getEquipOrBuilder(
          int index) {
        if (equipBuilder_ == null) {
          return equip_.get(index);  } else {
          return equipBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public java.util.List<? extends com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder> 
           getEquipOrBuilderList() {
        if (equipBuilder_ != null) {
          return equipBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(equip_);
        }
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder addEquipBuilder() {
        return getEquipFieldBuilder().addBuilder(
            com.ljh.gamedemo.proto.protoc.EquipProto.Equip.getDefaultInstance());
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder addEquipBuilder(
          int index) {
        return getEquipFieldBuilder().addBuilder(
            index, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.getDefaultInstance());
      }
      /**
       * <code>repeated .Equip equip = 5;</code>
       */
      public java.util.List<com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder> 
           getEquipBuilderList() {
        return getEquipFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.EquipProto.Equip, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder, com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder> 
          getEquipFieldBuilder() {
        if (equipBuilder_ == null) {
          equipBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.EquipProto.Equip, com.ljh.gamedemo.proto.protoc.EquipProto.Equip.Builder, com.ljh.gamedemo.proto.protoc.EquipProto.EquipOrBuilder>(
                  equip_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          equip_ = null;
        }
        return equipBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ResponseMall)
    }

    // @@protoc_insertion_point(class_scope:ResponseMall)
    private static final com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall();
    }

    public static com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMall>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMall>() {
      @java.lang.Override
      public ResponseMall parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMall(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMall> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMall> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.MsgMallProto.ResponseMall getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMall_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMall_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResponseMall_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResponseMall_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMsgMall.proto\032\013Items.proto\032\013Equip.prot" +
      "o\"F\n\013RequestMall\022\016\n\006userId\030\001 \001(\003\022\013\n\003cId\030" +
      "\002 \001(\003\022\032\n\004type\030\003 \001(\0162\014.RequestType\"y\n\014Res" +
      "ponseMall\022\016\n\006result\030\001 \001(\005\022\017\n\007content\030\002 \001" +
      "(\t\022\032\n\004type\030\003 \001(\0162\014.RequestType\022\025\n\005items\030" +
      "\004 \003(\0132\006.Items\022\025\n\005equip\030\005 \003(\0132\006.Equip* \n\013" +
      "RequestType\022\010\n\004MALL\020\000\022\007\n\003BUY\020\001B-\n\035com.lj" +
      "h.gamedemo.proto.protocB\014MsgMallProtob\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljh.gamedemo.proto.protoc.ItemsProto.getDescriptor(),
          com.ljh.gamedemo.proto.protoc.EquipProto.getDescriptor(),
        });
    internal_static_RequestMall_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMall_descriptor,
        new java.lang.String[] { "UserId", "CId", "Type", });
    internal_static_ResponseMall_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ResponseMall_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResponseMall_descriptor,
        new java.lang.String[] { "Result", "Content", "Type", "Items", "Equip", });
    com.ljh.gamedemo.proto.protoc.ItemsProto.getDescriptor();
    com.ljh.gamedemo.proto.protoc.EquipProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
