// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Trans.proto

package com.ljh.gamedemo.proto.protoc;

public final class TransProto {
  private TransProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trans)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    boolean hasPromoter();
    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.Role getPromoter();
    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getPromoterOrBuilder();

    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    boolean hasReceiver();
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.Role getReceiver();
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getReceiverOrBuilder();

    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    boolean hasGoods();
    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.GoodsProto.Goods getGoods();
    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder getGoodsOrBuilder();

    /**
     * <pre>
     * 金额
     * </pre>
     *
     * <code>int32 amount = 5;</code>
     */
    int getAmount();
  }
  /**
   * Protobuf type {@code Trans}
   */
  public  static final class Trans extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trans)
      TransOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trans.newBuilder() to construct.
    private Trans(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trans() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Trans();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trans(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder subBuilder = null;
              if (promoter_ != null) {
                subBuilder = promoter_.toBuilder();
              }
              promoter_ = input.readMessage(com.ljh.gamedemo.proto.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(promoter_);
                promoter_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder subBuilder = null;
              if (receiver_ != null) {
                subBuilder = receiver_.toBuilder();
              }
              receiver_ = input.readMessage(com.ljh.gamedemo.proto.protoc.RoleProto.Role.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiver_);
                receiver_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder subBuilder = null;
              if (goods_ != null) {
                subBuilder = goods_.toBuilder();
              }
              goods_ = input.readMessage(com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(goods_);
                goods_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {

              amount_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ljh.gamedemo.proto.protoc.TransProto.internal_static_Trans_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ljh.gamedemo.proto.protoc.TransProto.internal_static_Trans_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ljh.gamedemo.proto.protoc.TransProto.Trans.class, com.ljh.gamedemo.proto.protoc.TransProto.Trans.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int PROMOTER_FIELD_NUMBER = 2;
    private com.ljh.gamedemo.proto.protoc.RoleProto.Role promoter_;
    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    public boolean hasPromoter() {
      return promoter_ != null;
    }
    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.Role getPromoter() {
      return promoter_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : promoter_;
    }
    /**
     * <pre>
     * 发起人
     * </pre>
     *
     * <code>.Role promoter = 2;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getPromoterOrBuilder() {
      return getPromoter();
    }

    public static final int RECEIVER_FIELD_NUMBER = 3;
    private com.ljh.gamedemo.proto.protoc.RoleProto.Role receiver_;
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    public boolean hasReceiver() {
      return receiver_ != null;
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.Role getReceiver() {
      return receiver_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : receiver_;
    }
    /**
     * <pre>
     * 接收人
     * </pre>
     *
     * <code>.Role receiver = 3;</code>
     */
    public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getReceiverOrBuilder() {
      return getReceiver();
    }

    public static final int GOODS_FIELD_NUMBER = 4;
    private com.ljh.gamedemo.proto.protoc.GoodsProto.Goods goods_;
    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    public boolean hasGoods() {
      return goods_ != null;
    }
    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.GoodsProto.Goods getGoods() {
      return goods_ == null ? com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.getDefaultInstance() : goods_;
    }
    /**
     * <pre>
     * 物品
     * </pre>
     *
     * <code>.Goods goods = 4;</code>
     */
    public com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder getGoodsOrBuilder() {
      return getGoods();
    }

    public static final int AMOUNT_FIELD_NUMBER = 5;
    private int amount_;
    /**
     * <pre>
     * 金额
     * </pre>
     *
     * <code>int32 amount = 5;</code>
     */
    public int getAmount() {
      return amount_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (promoter_ != null) {
        output.writeMessage(2, getPromoter());
      }
      if (receiver_ != null) {
        output.writeMessage(3, getReceiver());
      }
      if (goods_ != null) {
        output.writeMessage(4, getGoods());
      }
      if (amount_ != 0) {
        output.writeInt32(5, amount_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (promoter_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getPromoter());
      }
      if (receiver_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getReceiver());
      }
      if (goods_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGoods());
      }
      if (amount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, amount_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ljh.gamedemo.proto.protoc.TransProto.Trans)) {
        return super.equals(obj);
      }
      com.ljh.gamedemo.proto.protoc.TransProto.Trans other = (com.ljh.gamedemo.proto.protoc.TransProto.Trans) obj;

      if (getId()
          != other.getId()) return false;
      if (hasPromoter() != other.hasPromoter()) return false;
      if (hasPromoter()) {
        if (!getPromoter()
            .equals(other.getPromoter())) return false;
      }
      if (hasReceiver() != other.hasReceiver()) return false;
      if (hasReceiver()) {
        if (!getReceiver()
            .equals(other.getReceiver())) return false;
      }
      if (hasGoods() != other.hasGoods()) return false;
      if (hasGoods()) {
        if (!getGoods()
            .equals(other.getGoods())) return false;
      }
      if (getAmount()
          != other.getAmount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      if (hasPromoter()) {
        hash = (37 * hash) + PROMOTER_FIELD_NUMBER;
        hash = (53 * hash) + getPromoter().hashCode();
      }
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      if (hasGoods()) {
        hash = (37 * hash) + GOODS_FIELD_NUMBER;
        hash = (53 * hash) + getGoods().hashCode();
      }
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getAmount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ljh.gamedemo.proto.protoc.TransProto.Trans prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trans}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trans)
        com.ljh.gamedemo.proto.protoc.TransProto.TransOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ljh.gamedemo.proto.protoc.TransProto.internal_static_Trans_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ljh.gamedemo.proto.protoc.TransProto.internal_static_Trans_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ljh.gamedemo.proto.protoc.TransProto.Trans.class, com.ljh.gamedemo.proto.protoc.TransProto.Trans.Builder.class);
      }

      // Construct using com.ljh.gamedemo.proto.protoc.TransProto.Trans.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        if (promoterBuilder_ == null) {
          promoter_ = null;
        } else {
          promoter_ = null;
          promoterBuilder_ = null;
        }
        if (receiverBuilder_ == null) {
          receiver_ = null;
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }
        if (goodsBuilder_ == null) {
          goods_ = null;
        } else {
          goods_ = null;
          goodsBuilder_ = null;
        }
        amount_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ljh.gamedemo.proto.protoc.TransProto.internal_static_Trans_descriptor;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.TransProto.Trans getDefaultInstanceForType() {
        return com.ljh.gamedemo.proto.protoc.TransProto.Trans.getDefaultInstance();
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.TransProto.Trans build() {
        com.ljh.gamedemo.proto.protoc.TransProto.Trans result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ljh.gamedemo.proto.protoc.TransProto.Trans buildPartial() {
        com.ljh.gamedemo.proto.protoc.TransProto.Trans result = new com.ljh.gamedemo.proto.protoc.TransProto.Trans(this);
        result.id_ = id_;
        if (promoterBuilder_ == null) {
          result.promoter_ = promoter_;
        } else {
          result.promoter_ = promoterBuilder_.build();
        }
        if (receiverBuilder_ == null) {
          result.receiver_ = receiver_;
        } else {
          result.receiver_ = receiverBuilder_.build();
        }
        if (goodsBuilder_ == null) {
          result.goods_ = goods_;
        } else {
          result.goods_ = goodsBuilder_.build();
        }
        result.amount_ = amount_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ljh.gamedemo.proto.protoc.TransProto.Trans) {
          return mergeFrom((com.ljh.gamedemo.proto.protoc.TransProto.Trans)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ljh.gamedemo.proto.protoc.TransProto.Trans other) {
        if (other == com.ljh.gamedemo.proto.protoc.TransProto.Trans.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.hasPromoter()) {
          mergePromoter(other.getPromoter());
        }
        if (other.hasReceiver()) {
          mergeReceiver(other.getReceiver());
        }
        if (other.hasGoods()) {
          mergeGoods(other.getGoods());
        }
        if (other.getAmount() != 0) {
          setAmount(other.getAmount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ljh.gamedemo.proto.protoc.TransProto.Trans parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ljh.gamedemo.proto.protoc.TransProto.Trans) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private com.ljh.gamedemo.proto.protoc.RoleProto.Role promoter_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> promoterBuilder_;
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public boolean hasPromoter() {
        return promoterBuilder_ != null || promoter_ != null;
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role getPromoter() {
        if (promoterBuilder_ == null) {
          return promoter_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : promoter_;
        } else {
          return promoterBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public Builder setPromoter(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (promoterBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          promoter_ = value;
          onChanged();
        } else {
          promoterBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public Builder setPromoter(
          com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (promoterBuilder_ == null) {
          promoter_ = builderForValue.build();
          onChanged();
        } else {
          promoterBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public Builder mergePromoter(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (promoterBuilder_ == null) {
          if (promoter_ != null) {
            promoter_ =
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.newBuilder(promoter_).mergeFrom(value).buildPartial();
          } else {
            promoter_ = value;
          }
          onChanged();
        } else {
          promoterBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public Builder clearPromoter() {
        if (promoterBuilder_ == null) {
          promoter_ = null;
          onChanged();
        } else {
          promoter_ = null;
          promoterBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder getPromoterBuilder() {
        
        onChanged();
        return getPromoterFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getPromoterOrBuilder() {
        if (promoterBuilder_ != null) {
          return promoterBuilder_.getMessageOrBuilder();
        } else {
          return promoter_ == null ?
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : promoter_;
        }
      }
      /**
       * <pre>
       * 发起人
       * </pre>
       *
       * <code>.Role promoter = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
          getPromoterFieldBuilder() {
        if (promoterBuilder_ == null) {
          promoterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder>(
                  getPromoter(),
                  getParentForChildren(),
                  isClean());
          promoter_ = null;
        }
        return promoterBuilder_;
      }

      private com.ljh.gamedemo.proto.protoc.RoleProto.Role receiver_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> receiverBuilder_;
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public boolean hasReceiver() {
        return receiverBuilder_ != null || receiver_ != null;
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role getReceiver() {
        if (receiverBuilder_ == null) {
          return receiver_ == null ? com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : receiver_;
        } else {
          return receiverBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public Builder setReceiver(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (receiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiver_ = value;
          onChanged();
        } else {
          receiverBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public Builder setReceiver(
          com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder builderForValue) {
        if (receiverBuilder_ == null) {
          receiver_ = builderForValue.build();
          onChanged();
        } else {
          receiverBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public Builder mergeReceiver(com.ljh.gamedemo.proto.protoc.RoleProto.Role value) {
        if (receiverBuilder_ == null) {
          if (receiver_ != null) {
            receiver_ =
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.newBuilder(receiver_).mergeFrom(value).buildPartial();
          } else {
            receiver_ = value;
          }
          onChanged();
        } else {
          receiverBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public Builder clearReceiver() {
        if (receiverBuilder_ == null) {
          receiver_ = null;
          onChanged();
        } else {
          receiver_ = null;
          receiverBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder getReceiverBuilder() {
        
        onChanged();
        return getReceiverFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      public com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder getReceiverOrBuilder() {
        if (receiverBuilder_ != null) {
          return receiverBuilder_.getMessageOrBuilder();
        } else {
          return receiver_ == null ?
              com.ljh.gamedemo.proto.protoc.RoleProto.Role.getDefaultInstance() : receiver_;
        }
      }
      /**
       * <pre>
       * 接收人
       * </pre>
       *
       * <code>.Role receiver = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder> 
          getReceiverFieldBuilder() {
        if (receiverBuilder_ == null) {
          receiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.RoleProto.Role, com.ljh.gamedemo.proto.protoc.RoleProto.Role.Builder, com.ljh.gamedemo.proto.protoc.RoleProto.RoleOrBuilder>(
                  getReceiver(),
                  getParentForChildren(),
                  isClean());
          receiver_ = null;
        }
        return receiverBuilder_;
      }

      private com.ljh.gamedemo.proto.protoc.GoodsProto.Goods goods_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.GoodsProto.Goods, com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder, com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder> goodsBuilder_;
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public boolean hasGoods() {
        return goodsBuilder_ != null || goods_ != null;
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.GoodsProto.Goods getGoods() {
        if (goodsBuilder_ == null) {
          return goods_ == null ? com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.getDefaultInstance() : goods_;
        } else {
          return goodsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public Builder setGoods(com.ljh.gamedemo.proto.protoc.GoodsProto.Goods value) {
        if (goodsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          goods_ = value;
          onChanged();
        } else {
          goodsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public Builder setGoods(
          com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder builderForValue) {
        if (goodsBuilder_ == null) {
          goods_ = builderForValue.build();
          onChanged();
        } else {
          goodsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public Builder mergeGoods(com.ljh.gamedemo.proto.protoc.GoodsProto.Goods value) {
        if (goodsBuilder_ == null) {
          if (goods_ != null) {
            goods_ =
              com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.newBuilder(goods_).mergeFrom(value).buildPartial();
          } else {
            goods_ = value;
          }
          onChanged();
        } else {
          goodsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public Builder clearGoods() {
        if (goodsBuilder_ == null) {
          goods_ = null;
          onChanged();
        } else {
          goods_ = null;
          goodsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder getGoodsBuilder() {
        
        onChanged();
        return getGoodsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      public com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder getGoodsOrBuilder() {
        if (goodsBuilder_ != null) {
          return goodsBuilder_.getMessageOrBuilder();
        } else {
          return goods_ == null ?
              com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.getDefaultInstance() : goods_;
        }
      }
      /**
       * <pre>
       * 物品
       * </pre>
       *
       * <code>.Goods goods = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.ljh.gamedemo.proto.protoc.GoodsProto.Goods, com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder, com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder> 
          getGoodsFieldBuilder() {
        if (goodsBuilder_ == null) {
          goodsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.ljh.gamedemo.proto.protoc.GoodsProto.Goods, com.ljh.gamedemo.proto.protoc.GoodsProto.Goods.Builder, com.ljh.gamedemo.proto.protoc.GoodsProto.GoodsOrBuilder>(
                  getGoods(),
                  getParentForChildren(),
                  isClean());
          goods_ = null;
        }
        return goodsBuilder_;
      }

      private int amount_ ;
      /**
       * <pre>
       * 金额
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public int getAmount() {
        return amount_;
      }
      /**
       * <pre>
       * 金额
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public Builder setAmount(int value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 金额
       * </pre>
       *
       * <code>int32 amount = 5;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trans)
    }

    // @@protoc_insertion_point(class_scope:Trans)
    private static final com.ljh.gamedemo.proto.protoc.TransProto.Trans DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ljh.gamedemo.proto.protoc.TransProto.Trans();
    }

    public static com.ljh.gamedemo.proto.protoc.TransProto.Trans getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trans>
        PARSER = new com.google.protobuf.AbstractParser<Trans>() {
      @java.lang.Override
      public Trans parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trans(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trans> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trans> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ljh.gamedemo.proto.protoc.TransProto.Trans getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trans_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trans_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Trans.proto\032\nRole.proto\032\013Goods.proto\"l" +
      "\n\005Trans\022\n\n\002id\030\001 \001(\003\022\027\n\010promoter\030\002 \001(\0132\005." +
      "Role\022\027\n\010receiver\030\003 \001(\0132\005.Role\022\025\n\005goods\030\004" +
      " \001(\0132\006.Goods\022\016\n\006amount\030\005 \001(\005B+\n\035com.ljh." +
      "gamedemo.proto.protocB\nTransProtob\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ljh.gamedemo.proto.protoc.RoleProto.getDescriptor(),
          com.ljh.gamedemo.proto.protoc.GoodsProto.getDescriptor(),
        });
    internal_static_Trans_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trans_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trans_descriptor,
        new java.lang.String[] { "Id", "Promoter", "Receiver", "Goods", "Amount", });
    com.ljh.gamedemo.proto.protoc.RoleProto.getDescriptor();
    com.ljh.gamedemo.proto.protoc.GoodsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
